### ISSUE TITLE
Verify that exporting a connection for a Mach service works correctly

### ISSUE THREAD

**Issue by amomchilov** [trilemma-dev/SecureXPC#33]
https://github.com/trilemma-dev/SecureXPC/blob/ab4e612fd83ae3afef76e455831ae3ce9fe07f0d/Sources/SecureXPC/Server/XPCMachServer.swift#L204-L208

> Fatal-error this code path to say that it's untested, and treat it as effectively not-yet-implemented.
>
> ...
> 
> Let's go with option 2 for now. I'd volunteer to try testing it out, but between end of year busyness at work and heading off on holiday soon I just won't have time before early January. Can revisit it then.

_Originally posted by @jakaplan in https://github.com/trilemma-dev/SecureXPC/pull/23#discussion_r769131546_

**Comment by jakaplan** [comment]
I've very briefly started looking into this, but haven't done any actual testing yet. I'd be rather surprised if what we currently have works in all cases as it's inconsistent:
 - `XPCAnonymousServer` returns the listener connection, which absolutely works as demonstrated by our tests
 - `XPCMachServer` returns the listener connection if the server has been started, otherwise `fatalError`s out
     - I haven't tested this yet, but I can imagine it work as it's consistent with `XPCAnonymousServer`
 - `XPCServiceServer` returns the most recent client connection it's received (but in practice I think it'd only ever receive one?)
     - My hunch is this doesn't actually work, although I don't currently have an XPC Service implementation so it'll take me a bit to create a setup to test this out
     - There is no concept of a listener connection for an XPC Service; `xpc_main` is the one and only entry point

If it's true that there's no equivalent for XPC Services and therefore no way to return an `XPCServerEndpoint`, I think we could do one or both of the following:
 - Move the `endpoint` property to `NonBlockingStartable` (and rename it)
 - Have the `start()` function defined by `NonBlockingStartable` return the `NonBlockingStartable`
     - Only doing this might turn out to be inconvenient for anyone trying to pass around an endpoint for a Mach service

**Comment by jakaplan** [comment]
I've confirmed that exporting a connection for an `XPCMachServer` works correctly. So in terms of exactly this issue, I'll put up a PR soon to address it.

Since this does work and it differs from `XPCServiceServer`'s behavior, educated guess that the `endpoint` for the `XPCServiceServer` doesn't work properly (and probably can't work). I'll create a new issue for this.
